import type { ReactNode } from 'react';
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, type TextInputProps, type ViewStyle, View } from 'react-native';
import { colors, elevation, layout, radius, spacing, typography } from './theme';
export * from './theme';

export function ScreenContainer({ children, scroll = true, style }: { children: ReactNode; scroll?: boolean; style?: ViewStyle }) {
  const content = <View style={[styles.screenContent, style]}>{children}</View>;
  return <SafeAreaView style={styles.safe}>{scroll ? <ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled">{content}</ScrollView> : content}</SafeAreaView>;
}
export function Button({ label, onPress, variant = 'primary', disabled = false }: { label: string; onPress: () => void; variant?: 'primary' | 'secondary' | 'ghost'; disabled?: boolean }) {
  return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.button, styles[`button_${variant}`], pressed && styles.pressed, disabled && styles.disabled]}><Text style={[styles.buttonLabel, variant === 'primary' ? styles.buttonLabelDark : styles.buttonLabelLight]}>{label}</Text></Pressable>;
}
export function Input({ label, error, endAdornment, ...props }: TextInputProps & { label: string; error?: string; endAdornment?: ReactNode }) {
  return <View style={styles.field}><Text style={styles.label}>{label}</Text><View style={[styles.inputWrap, error && styles.inputError]}><TextInput {...props} placeholderTextColor={colors.muted} style={styles.input}/>{endAdornment}</View>{error ? <Text style={styles.error}>{error}</Text> : null}</View>;
}
export function SearchInput(props: TextInputProps) { return <View style={styles.search}><Text style={styles.searchIcon}>⌕</Text><TextInput {...props} accessibilityLabel={props.accessibilityLabel ?? 'البحث'} placeholderTextColor={colors.muted} style={styles.input}/></View>; }
export function Card({ children, style }: { children: ReactNode; style?: ViewStyle }) { return <View style={[styles.card, style]}>{children}</View>; }
export function Badge({ label, tone = 'neutral' }: { label: string; tone?: 'neutral' | 'gold' | 'success' | 'danger' }) { return <View style={[styles.badge, styles[`badge_${tone}`]]}><Text style={[styles.badgeText, styles[`badgeText_${tone}`]]}>{label}</Text></View>; }
export function SectionHeader({ title, action, onAction }: { title: string; action?: string; onAction?: () => void }) { return <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>{title}</Text>{action ? <Pressable onPress={onAction} hitSlop={10}><Text style={styles.sectionAction}>{action}</Text></Pressable> : null}</View>; }
export function EmptyState({ title, message }: { title: string; message: string }) { return <View style={styles.state}><Text style={styles.stateTitle}>{title}</Text><Text style={styles.stateBody}>{message}</Text></View>; }
export function ErrorState({ message, onRetry }: { message: string; onRetry?: () => void }) { return <View style={styles.state}><Text style={[styles.stateTitle, { color: colors.danger }]}>تعذر تحميل البيانات</Text><Text style={styles.stateBody}>{message}</Text>{onRetry ? <Button label="إعادة المحاولة" onPress={onRetry} variant="secondary"/> : null}</View>; }
export function LoadingState() { return <View style={styles.state}><ActivityIndicator color={colors.gold600}/><Text style={styles.stateBody}>جارٍ التحميل…</Text></View>; }
export function OfflineBanner() { return <View style={styles.offline}><Text style={styles.offlineText}>أنت غير متصل — ستُحفظ تغييراتك على هذا الجهاز</Text></View>; }
export function MatterCard({ reference, title, client, status }: { reference: string; title: string; client: string; status: string }) { return <Card><View style={styles.rowBetween}><Badge label={status} tone="success"/><Text style={styles.reference}>{reference}</Text></View><Text style={styles.cardTitle}>{title}</Text><Text style={styles.cardMeta}>{client}</Text></Card>; }
export function ClientCard({ name, phone }: { name: string; phone: string }) { return <Card><Text style={styles.cardTitle}>{name}</Text><Text style={styles.cardMeta}>{phone}</Text></Card>; }

const rtlText = { textAlign: 'right' as const, writingDirection: 'rtl' as const };
const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.canvas }, scroll: { flexGrow: 1 }, screenContent: { width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', padding: layout.screenGutter, gap: spacing.md },
  button: { minHeight: layout.minTouchTarget, borderRadius: radius.md, paddingHorizontal: spacing.md, justifyContent: 'center', alignItems: 'center', borderWidth: 1 }, button_primary: { backgroundColor: colors.gold500, borderColor: colors.gold500 }, button_secondary: { backgroundColor: colors.navy900, borderColor: colors.navy900 }, button_ghost: { backgroundColor: 'transparent', borderColor: colors.border }, buttonLabel: { fontFamily: typography.medium, fontSize: 15 }, buttonLabelDark: { color: colors.navy950 }, buttonLabelLight: { color: colors.white }, pressed: { opacity: .78 }, disabled: { opacity: .45 },
  field: { gap: spacing.xs }, label: { ...rtlText, color: colors.ink, fontFamily: typography.medium, fontSize: 13 }, inputWrap: { minHeight: 52, flexDirection: 'row-reverse', alignItems: 'center', gap: spacing.xs, paddingHorizontal: spacing.md, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, backgroundColor: colors.surface }, input: { flex: 1, minHeight: 48, ...rtlText, color: colors.ink, fontFamily: typography.regular, fontSize: 14 }, inputError: { borderColor: colors.danger }, error: { ...rtlText, color: colors.danger, fontSize: 12 },
  search: { minHeight: 52, flexDirection: 'row-reverse', alignItems: 'center', gap: spacing.sm, paddingHorizontal: spacing.md, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, backgroundColor: colors.surface, ...elevation.card }, searchIcon: { color: colors.gold600, fontSize: 25 },
  card: { padding: spacing.md, gap: spacing.xs, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, backgroundColor: colors.surface, ...elevation.card }, badge: { alignSelf: 'flex-start', borderRadius: radius.full, paddingVertical: 4, paddingHorizontal: spacing.sm }, badge_neutral: { backgroundColor: '#EFF1F2' }, badge_gold: { backgroundColor: colors.gold100 }, badge_success: { backgroundColor: '#E5F3EB' }, badge_danger: { backgroundColor: '#F9E9E8' }, badgeText: { fontSize: 11, fontFamily: typography.medium }, badgeText_neutral: { color: colors.muted }, badgeText_gold: { color: colors.gold600 }, badgeText_success: { color: colors.success }, badgeText_danger: { color: colors.danger },
  sectionHeader: { minHeight: 36, flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center' }, sectionTitle: { ...rtlText, color: colors.navy900, fontFamily: typography.medium, fontSize: 17 }, sectionAction: { color: colors.gold600, fontFamily: typography.medium, fontSize: 12 }, state: { minHeight: 160, justifyContent: 'center', alignItems: 'center', gap: spacing.sm, padding: spacing.xl }, stateTitle: { ...rtlText, color: colors.navy900, fontFamily: typography.medium, fontSize: 16 }, stateBody: { ...rtlText, color: colors.muted, fontSize: 13, lineHeight: 22 }, offline: { paddingVertical: spacing.xs, paddingHorizontal: spacing.md, backgroundColor: colors.gold100 }, offlineText: { ...rtlText, color: colors.navy900, fontSize: 11 }, rowBetween: { flexDirection: 'row-reverse', justifyContent: 'space-between' }, reference: { ...rtlText, color: colors.muted, fontSize: 12 }, cardTitle: { ...rtlText, color: colors.ink, fontFamily: typography.medium, fontSize: 15 }, cardMeta: { ...rtlText, color: colors.muted, fontSize: 12 },
});
