import { useState } from 'react';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { Button, colors, Input, ScreenContainer, spacing, typography } from '@maktabi/ui';
import { BrandMark } from '@/components/BrandMark';
export default function LoginScreen() {
  const [identity, setIdentity] = useState(''); const [password, setPassword] = useState(''); const [visible, setVisible] = useState(false); const [remember, setRemember] = useState(true); const [error, setError] = useState('');
  const login = () => { if (!identity.trim() || !password) { setError('أدخل اسم المستخدم وكلمة المرور للمتابعة'); return; } setError(''); router.replace('/(tabs)'); };
  return <KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScreenContainer style={styles.content}><BrandMark/><View style={styles.heading}><Text style={styles.title}>أهلاً بك في نظام مكتبي</Text><Text style={styles.subtitle}>سجّل الدخول إلى مساحة عملك القانونية</Text></View><Input label="اسم المستخدم أو البريد الإلكتروني" value={identity} onChangeText={setIdentity} autoCapitalize="none" autoComplete="username" placeholder="أدخل اسم المستخدم" error={error || undefined}/><Input label="كلمة المرور" value={password} onChangeText={setPassword} secureTextEntry={!visible} autoComplete="current-password" placeholder="أدخل كلمة المرور" endAdornment={<Pressable accessibilityRole="button" accessibilityLabel={visible ? 'إخفاء كلمة المرور' : 'إظهار كلمة المرور'} onPress={() => setVisible(!visible)} hitSlop={10}><Ionicons name={visible ? 'eye-off-outline' : 'eye-outline'} size={22} color={colors.muted}/></Pressable>}/><View style={styles.options}><Pressable onPress={() => setRemember(!remember)} style={styles.remember}><View style={[styles.checkbox, remember && styles.checked]}>{remember ? <Ionicons name="checkmark" color={colors.navy950} size={14}/> : null}</View><Text style={styles.optionText}>تذكرني</Text></Pressable><Pressable><Text style={styles.link}>نسيت كلمة المرور؟</Text></Pressable></View><Button label="تسجيل الدخول" onPress={login}/><Text style={styles.demo}>تسجيل دخول تجريبي — لا تُدخل بيانات حقيقية</Text></ScreenContainer></KeyboardAvoidingView>;
}
const rtl = { textAlign: 'right' as const, writingDirection: 'rtl' as const };
const styles = StyleSheet.create({ flex: { flex: 1, backgroundColor: colors.canvas }, content: { flexGrow: 1, justifyContent: 'center', gap: spacing.lg }, heading: { alignItems: 'center', gap: spacing.xs }, title: { ...rtl, color: colors.navy900, fontFamily: typography.medium, fontSize: 19 }, subtitle: { ...rtl, color: colors.muted, fontSize: 13 }, options: { flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center' }, remember: { minHeight: 44, flexDirection: 'row-reverse', alignItems: 'center', gap: spacing.xs }, checkbox: { width: 20, height: 20, borderWidth: 1, borderColor: colors.gold600, borderRadius: 5, alignItems: 'center', justifyContent: 'center' }, checked: { backgroundColor: colors.gold500 }, optionText: { color: colors.ink, fontSize: 12 }, link: { color: colors.navy800, fontFamily: typography.medium, fontSize: 12 }, demo: { ...rtl, color: colors.muted, textAlign: 'center', fontSize: 10 } });
