import { useState } from 'react';
import { View } from 'react-native';
import type { Matter } from '@maktabi/domain';
import { BodyText, Button, Card, ChoiceField, Input, SectionHeader, featureStyles as s } from '@maktabi/ui';
import { newId, officeRepository } from '@/data/repositories';
import { expenseCategories } from '@/data/office';
import { paidTotal, parseAmount, trustBalance, outstandingExpenses, type MatterWorkflow } from '@/data/workflow';
import { money } from '../shared/hooks';
import type { RunOperation } from './ProcedurePanel';
import { ServiceNotice } from '@/components/ServiceNotice';

const today = () => new Date().toLocaleDateString('en-CA');
export function FinancePanel({ matter, workflow: w, run, busy, closed }: { matter: Matter; workflow: MatterWorkflow; run: RunOperation; busy: boolean; closed: boolean }) {
  const [tab, setTab] = useState('fees'); const [amount, setAmount] = useState(''); const [date, setDate] = useState(today); const [title, setTitle] = useState(''); const [stageId, setStageId] = useState(''); const [method, setMethod] = useState('نقدي'); const [receiver, setReceiver] = useState(''); const [proofId, setProofId] = useState(''); const [replacesId, setReplacesId] = useState(''); const [reason, setReason] = useState(''); const [category, setCategory] = useState(expenseCategories[0]!); const [source, setSource] = useState('TRUST');
  const paid = paidTotal(w); const id = matter.id;
  const stageOptions = [{ value: '', label: 'عام / دون مرحلة' }, ...w.stages.map((s) => ({ value: s.id, label: `${s.name} · ${s.reference}` }))];
  const documentOptions = [{ value: '', label: 'دون مرفق' }, ...w.documents.map((d) => ({ value: d.id, label: d.title }))];
  const fields = <><Input label="المبلغ بالجنيه السوداني" keyboardType="decimal-pad" value={amount} onChangeText={setAmount}/><Input label="التاريخ (YYYY-MM-DD)" value={date} onChangeText={setDate}/></>;
  const reset = () => { setAmount(''); setTitle(''); setProofId(''); setReplacesId(''); };
  return <><Card><SectionHeader title="حساب القضية"/><BodyText>أتعاب المكتب: {money(w.agreedFees)} · مدفوع: {money(paid)} · متبقٍ: {money(w.agreedFees - paid)}</BodyText><BodyText>رصيد أمانة العميل: {money(trustBalance(w))}</BodyText><BodyText>مصروفات مستحقة على العميل: {money(outstandingExpenses(w))}</BodyText><BodyText muted>تُحسب الأمانات والمصروفات منفصلة عن أتعاب المحامي.</BodyText></Card>
    <ChoiceField label="القسم المالي" value={tab} onChange={(v) => { setTab(v); reset(); }} options={[{ value: 'fees', label: 'اتفاق الأتعاب والاستحقاقات' }, { value: 'payments', label: 'الدفعات والإيصالات' }, { value: 'trust', label: 'أمانات العميل' }, { value: 'expenses', label: 'الرسوم والمصروفات' }]}/>
    {tab === 'fees' ? <Card><SectionHeader title="بنود اتفاق الأتعاب"/>{w.installments.map((f) => <View key={f.id} style={s.item}><BodyText>{f.title} · {money(f.amount)} · {f.dueDate}</BodyText><BodyText muted>{w.stages.find((s) => s.id === f.stageId)?.name}</BodyText>{!closed ? <Button label={`حذف بند: ${f.title}`} variant="secondary" disabled={busy} onPress={() => void run(() => officeRepository.saveInstallments(id, w.installments.filter((i) => i.id !== f.id)), 'تم تحديث الاتفاق')}/> : null}</View>)}
      {!closed ? <><Input label="وصف بند الأتعاب" value={title} onChangeText={setTitle}/>{fields}<BodyText muted>التاريخ هو تاريخ استحقاق هذا البند. لإتفاق ثابت أضف بنداً واحداً.</BodyText><ChoiceField label="المرحلة المرتبطة بالأتعاب" value={stageId} onChange={setStageId} options={stageOptions}/><Button label="حفظ بند الأتعاب" disabled={busy} onPress={() => void run(async () => { await officeRepository.saveInstallments(id, [...w.installments, { id: newId(), title, amount: parseAmount(amount), dueDate: date, stageId: stageId || undefined }]); reset(); }, 'تم حفظ اتفاق الأتعاب')}/></> : null}</Card> : null}
    {tab === 'payments' ? <><Card><SectionHeader title="تسجيل دفعة وإصدار إيصال"/>{!closed ? <>{fields}<ChoiceField label="طريقة الدفع" value={method} onChange={setMethod} options={['نقدي', 'بنكك', 'تحويل بنكي', 'أخرى'].map((value) => ({ value, label: value }))}/><Input label="اسم مستلم الدفعة" value={receiver} onChangeText={setReceiver}/><ChoiceField label="إشعار التحويل من مستندات القضية" value={proofId} onChange={setProofId} options={documentOptions}/><ChoiceField label="بديل لإيصال ملغى (اختياري)" value={replacesId} onChange={setReplacesId} options={[{ value: '', label: 'دفعة جديدة' }, ...w.receipts.filter((r) => r.status === 'CANCELLED').map((r) => ({ value: r.id, label: r.number }))]}/><Button label="تسجيل الدفعة وإصدار الإيصال" disabled={busy} onPress={() => void run(async () => { const at = new Date(`${date}T12:00:00`); if (!Number.isFinite(at.getTime()) || at.toLocaleDateString('en-CA') !== date) throw new Error('التاريخ غير صحيح'); await officeRepository.issueReceipt(id, { id: newId(), amount: parseAmount(amount), date: at.toISOString(), method, receiver, proofId: proofId || undefined, replacesId: replacesId || undefined }); reset(); }, 'تم تسجيل الدفعة وإصدار إيصال مرقم')}/></> : null}
      <BodyText muted>التحويل المسجل هنا يراجعه المكتب يدوياً؛ لا يتم تأكيده من البنك آلياً.</BodyText></Card>
      <Card><SectionHeader title="سجل الإيصالات"/><Input label="سبب إلغاء الإيصال عند التصحيح" value={reason} onChangeText={setReason}/>{w.receipts.map((r) => <View key={r.id} style={s.item}><BodyText>{r.number} · {r.status === 'CANCELLED' ? 'ملغى' : 'ساري'}</BodyText><BodyText>{money(r.amount)} · {r.method} · {new Date(r.date).toLocaleDateString('ar-SD')}</BodyText><BodyText>المستلم: {r.receiver || 'غير مسجل'}</BodyText>{r.cancellationReason ? <BodyText muted>{r.cancellationReason}</BodyText> : null}{!closed && r.status !== 'CANCELLED' ? <Button label={`إلغاء: ${r.number}`} variant="secondary" disabled={busy || !reason.trim()} onPress={() => void run(() => officeRepository.cancelReceipt(id, r.id, reason), 'تم إلغاء الإيصال مع بقاء رقمه')}/> : null}</View>)}</Card><ServiceNotice service="payments"/></> : null}
    {tab === 'trust' ? <Card><SectionHeader title="أمانة العميل"/>{!closed ? <>{fields}<Input label="بيان الإيداع" value={title} onChangeText={setTitle}/><Button label="تسجيل إيداع الأمانة" disabled={busy} onPress={() => void run(async () => { await officeRepository.depositTrust(id, { id: newId(), amount: parseAmount(amount), date, description: title }); reset(); }, 'تم إيداع الأمانة')}/></> : null}{w.deposits.map((d) => <BodyText key={d.id}>{d.date} · {d.description} · {money(d.amount)}</BodyText>)}{w.deposits.length && trustBalance(w) <= 10000 ? <BodyText>رصيد الأمانة منخفض؛ راجع العميل لتجديده.</BodyText> : null}</Card> : null}
    {tab === 'expenses' ? <Card><SectionHeader title="الرسوم والمصروفات"/>{!closed ? <>{fields}<ChoiceField label="نوع المصروف" value={category} onChange={setCategory} options={expenseCategories.map((value) => ({ value, label: value }))}/><Input label="الجهة أو مستلم المصروف" value={receiver} onChangeText={setReceiver}/><ChoiceField label="احتساب المصروف" value={source} onChange={setSource} options={[{ value: 'TRUST', label: 'خصم من أمانة العميل' }, { value: 'RECEIVABLE', label: 'مستحق على العميل' }]}/><ChoiceField label="المرحلة المرتبطة بالمصروف" value={stageId} onChange={setStageId} options={stageOptions}/><ChoiceField label="فاتورة المصروف من مستندات القضية" value={proofId} onChange={setProofId} options={documentOptions}/><Button label="تسجيل المصروف" disabled={busy} onPress={() => void run(async () => { await officeRepository.recordExpense(id, { id: newId(), amount: parseAmount(amount), date, category, recipient: receiver, source: source as 'TRUST' | 'RECEIVABLE', stageId: stageId || undefined, billId: proofId || undefined }); reset(); }, 'تم تسجيل المصروف وتحديث الحساب')}/><Input label="سبب إلغاء مصروف عند التصحيح" value={reason} onChangeText={setReason}/></> : null}
      {w.expenses.map((e) => <View key={e.id} style={s.item}><BodyText>{e.category} · {e.recipient} · {money(e.amount)}</BodyText><BodyText muted>{e.date} · {e.voidReason ? `ملغى: ${e.voidReason}` : e.source === 'TRUST' ? 'من الأمانة' : 'مستحق على العميل'}</BodyText>{!closed && !e.voidReason ? <Button label={`إلغاء مصروف: ${e.category}`} variant="secondary" disabled={busy || !reason.trim()} onPress={() => void run(() => officeRepository.voidExpense(id, e.id, reason), 'تم إلغاء المصروف وتحديث الرصيد')}/> : null}</View>)}
    </Card> : null}
  </>;
}
