import { Ionicons } from '@expo/vector-icons';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import type { DashboardSnapshot } from '@maktabi/domain';
import { Badge, Card, colors, ErrorState, layout, LoadingState, SearchInput, SectionHeader, spacing, typography } from '@maktabi/ui';
import { AppHeader } from '@/components/AppHeader';
import { dashboardRepository } from '@/data/mockDashboardRepository';
const time = new Intl.DateTimeFormat('ar-SD', { hour: 'numeric', minute: '2-digit', hour12: true, timeZone: 'UTC' });
const number = new Intl.NumberFormat('ar-SD', { maximumFractionDigits: 0 });
export default function DashboardScreen() {
  const [data, setData] = useState<DashboardSnapshot>(); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async () => { try { setError(''); setData(await dashboardRepository.getSnapshot()); } catch { setError('تحقق من البيانات المحلية وحاول مرة أخرى.'); } finally { setRefreshing(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const activity = useMemo(() => data?.recentActivity.filter((item) => `${item.title} ${item.detail}`.includes(query.trim())) ?? [], [data, query]);
  if (error) return <View style={styles.flex}><AppHeader/><ErrorState message={error} onRetry={() => void load()}/></View>;
  if (!data) return <View style={styles.flex}><AppHeader/><LoadingState/></View>;
  const firstName = data.currentUser.fullName.split(' ')[0] ?? data.currentUser.fullName;
  return <View style={styles.flex}><AppHeader/><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} tintColor={colors.gold600}/>}>
    <View style={styles.welcome}><Text style={styles.greeting}>صباح الخير، {firstName}</Text><Text style={styles.office}>{data.office.name}</Text></View>
    <SearchInput value={query} onChangeText={setQuery} placeholder="ابحث في الملفات والعملاء والمستندات" returnKeyType="search"/>
    <Card><SectionHeader title="جلسات اليوم" action={`${data.todaysSessions.length} جلسات`}/>{data.todaysSessions.map((session) => <Pressable key={session.id} style={styles.listRow}><Text style={styles.chevron}>‹</Text><View style={styles.rowText}><Text numberOfLines={1} style={styles.itemTitle}>{session.title}</Text><Text numberOfLines={1} style={styles.itemMeta}>{session.authority}{session.room ? ` · ${session.room}` : ''}</Text></View><Text style={styles.time}>{time.format(new Date(session.startsAt))}</Text></Pressable>)}</Card>
    <Card><SectionHeader title="المواعيد المهمة" action="عرض الكل"/>{data.upcomingDeadlines.map((deadline, index) => <View key={deadline.id} style={styles.listRow}>{deadline.priority === 'URGENT' ? <Badge label="عاجل" tone="danger"/> : <Badge label="قريب" tone="gold"/>}<View style={styles.rowText}><Text numberOfLines={2} style={styles.itemTitle}>{deadline.title}</Text><Text style={styles.itemMeta}>موعد أدخله المستخدم · {index ? '٣٠ سبتمبر' : '٢٧ سبتمبر'}</Text></View></View>)}</Card>
    <View style={styles.metrics}><Card style={styles.metric}><View style={styles.metricIcon}><Ionicons name="folder-open-outline" size={22} color={colors.white}/></View><Text style={styles.metricLabel}>الملفات النشطة</Text><Text style={styles.metricValue}>{number.format(data.activeMatters)}</Text></Card><Card style={styles.metric}><View style={[styles.metricIcon, styles.metricIconGold]}><Ionicons name="cash-outline" size={22} color={colors.navy950}/></View><Text style={styles.metricLabel}>الأتعاب المستحقة</Text><Text numberOfLines={1} adjustsFontSizeToFit style={styles.metricValue}>{number.format(data.outstandingFees.amountMinor / 100)} ج.س</Text><Text style={styles.warning}>{data.overdueFeeItems} عناصر تحتاج متابعة</Text></Card></View>
    <Card><SectionHeader title="إجراءات سريعة"/><View style={styles.quickGrid}>{[['folder-open-outline','ملف جديد'],['person-add-outline','عميل جديد'],['camera-outline','تصوير مستند'],['cash-outline','تسجيل دفعة']].map(([icon,label]) => <Pressable key={label} accessibilityRole="button" onPress={() => Alert.alert(label!, 'ستتوفر هذه الوظيفة في دفعة لاحقة.')} style={styles.quick}><View style={styles.quickIcon}><Ionicons name={icon as never} size={23} color={colors.gold600}/></View><Text style={styles.quickLabel}>{label}</Text></Pressable>)}</View></Card>
    <Card><SectionHeader title="آخر النشاطات" action="عرض السجل"/>{activity.length ? activity.map((item) => <View key={item.id} style={styles.activity}><View style={styles.activityDot}/><View style={styles.rowText}><Text style={styles.itemTitle}>{item.title}</Text><Text style={styles.itemMeta}>{item.detail}</Text></View><Text style={styles.when}>حديثاً</Text></View>) : <Text style={styles.empty}>لا توجد نتائج مطابقة لبحثك</Text>}</Card>
    <Text style={styles.disclaimer}>جميع الأسماء والمواعيد المعروضة بيانات تجريبية غير قانونية أو ملزمة.</Text>
  </ScrollView></View>;
}
const rtl = { textAlign: 'right' as const, writingDirection: 'rtl' as const };
const styles = StyleSheet.create({ flex: { flex: 1, backgroundColor: colors.canvas }, content: { width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', padding: layout.screenGutter, paddingBottom: spacing.xxl, gap: spacing.md }, welcome: { gap: 2 }, greeting: { ...rtl, color: colors.gold600, fontFamily: typography.medium, fontSize: 13 }, office: { ...rtl, color: colors.navy950, fontFamily: typography.medium, fontSize: 21 }, listRow: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderTopWidth: 1, borderTopColor: colors.border, paddingVertical: spacing.sm }, rowText: { flex: 1, gap: 3 }, itemTitle: { ...rtl, color: colors.ink, fontFamily: typography.medium, fontSize: 13 }, itemMeta: { ...rtl, color: colors.muted, fontSize: 10, lineHeight: 17 }, time: { width: 69, ...rtl, color: colors.navy800, fontFamily: typography.medium, fontSize: 12 }, chevron: { color: colors.muted, fontSize: 24 }, metrics: { flexDirection: 'row-reverse', gap: spacing.sm }, metric: { flex: 1, minWidth: 0 }, metricIcon: { width: 42, height: 42, borderRadius: 11, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.navy800 }, metricIconGold: { backgroundColor: colors.gold500 }, metricLabel: { ...rtl, color: colors.muted, fontSize: 10 }, metricValue: { ...rtl, color: colors.navy950, fontFamily: typography.medium, fontSize: 18 }, warning: { ...rtl, color: colors.danger, fontSize: 9 }, quickGrid: { flexDirection: 'row-reverse', justifyContent: 'space-between', gap: spacing.xs }, quick: { minHeight: 76, flex: 1, alignItems: 'center', gap: spacing.xs }, quickIcon: { width: 45, height: 45, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: colors.gold100 }, quickLabel: { ...rtl, color: colors.ink, textAlign: 'center', fontFamily: typography.medium, fontSize: 10 }, activity: { minHeight: 58, flexDirection: 'row-reverse', alignItems: 'center', gap: spacing.sm, borderTopWidth: 1, borderTopColor: colors.border, paddingVertical: spacing.sm }, activityDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.gold500 }, when: { color: colors.muted, fontSize: 9 }, empty: { ...rtl, color: colors.muted, textAlign: 'center', padding: spacing.lg }, disclaimer: { ...rtl, color: colors.muted, textAlign: 'center', fontSize: 9, lineHeight: 16 } });
